SPK_NAME = unzip
SPK_VERS = 1.0
SPK_REV = 0

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = This fucking guy
DESCRIPTION = Its fucking zip who cares
DISPLAY_NAME = stunnel TLS Proxy
STARTABLE = no
CHANGELOG = Nigga really

LICENSE  = who cares license

SERVICE_USER = auto

SPK_COMMANDS = bin/funzip bin/unzip bin/unzipsfx bin/zipgrep bin/zipinfo

include ../../mk/spksrc.spk.mk
