SPK_NAME = hashdeep
SPK_VERS = 1
SPK_REV = 0

DEPENDS = cross/hashdeep

REQUIRED_MIN_DSM = 7.0

MAINTAINER = This fucking guy
DESCRIPTION = This is md5deep, a set of cross-platform tools to compute hashes, or message digests, for any number of files while optionally recursively digging through the directory structure. It can also take a list of known hashes and display the filenames of input files whose hashes either do or do not match any of the known hashes. This version supports MD5, SHA-1, SHA-256, Tiger, and Whirlpool hashes.
DISPLAY_NAME = Hashdeep

STARTABLE = no
HOMEPAGE = https://github.com/jessek/hashdeep?
LICENSE  = Public Domain, GPL

SPK_COMMANDS += bin/hashdeep

include ../../mk/spksrc.spk.mk

